// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzvbzpsklggnvjcjsfla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6dmJ6cHNrbGdnbnZqY2pzZmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Nzg2OTEsImV4cCI6MjA2NTQ1NDY5MX0.NPFhOT1kAnXabmoVNM4FUk-uF_ap6WdOpLYssW3E3C0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);